### ISSUE TITLE
Not able to set duration to stay notification at screen

### ISSUE THREAD

**Issue by yasirshahzad918** [Gabrielr47/easyNotify#1]
Hi Sir, I'm using your library called easyNotify. I really love it and I just have one issue now. Is there a way to set notification duration to stay at screen. currently it has auto time set. I need your help sir. please guide

**Comment by gabriel-rodrigues-42** [comment]
Hi,

Yes you can use **requireInteraction** parameter, example:

```
var options = {
    title: 'my title',
    options: {
      body: 'my content',
      requireInteraction: true // <-- here
    }
  };

 $("#easyNotify").easyNotify(options);

```

> **requireInteraction**: Indicates that on devices with sufficiently large screens, a notification should remain active until the user clicks or dismisses it. If this value is absent or false, the desktop version of Chrome will auto-minimize notifications after approximately twenty seconds. The default value is false.

You can see more options here:  https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by yasirshahzad918** [comment]
Thank you so much sir for help :-)
