### ISSUE TITLE
html en notificación

### ISSUE THREAD

**Issue by joelmiguelvalente** [Gabrielr47/easyNotify#2]
Hola, quiero saber como puedo hacer para que las notificaciones acepte HTML ya que si en la opción **body** se le coloca lo siguente
`body: 'Este es el <b>cuerpo</b>'`
y lo que muestra es esto
`Este es el <b>cuerpo</b>`

**Comment by gabriel-rodrigues-42** [comment]
Hi Joel, 

Unfortunately this API supports only string as you can see in this official documentation:

https://developer.mozilla.org/en-US/docs/Web/API/Notification/body
